/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package notepad;

import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import static notepad.Themes.Info;

/**
 *
 * @author sachindehury2015@gmail.com
 */
public class About extends javax.swing.JFrame {

    /**
     * Creates new form About
     */
    public  About() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        About_Panel = new javax.swing.JPanel();
        About_Label = new javax.swing.JLabel();
        Exit_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");
        setLocation(new java.awt.Point(500, 200));
        setName("About_Frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(250, 250));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        About_Panel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        About_Panel.setMaximumSize(new java.awt.Dimension(250, 250));
        About_Panel.setPreferredSize(new java.awt.Dimension(360, 240));

        About_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        About_Label.setText("<html>"+
            "<body>"+
            "Developed By :<br>"+
            "Sachin Dehury<br>"+
            "@Speed Inc.<br>"+
            "E-Mail : sachindehury2015@gmail.com<br>"+
            "Version : 2.02 Beta<br>"+
            "Build Date : 26.06.2018<br>"+
            "Update Date : 22.03.2020<br>"+
            "<body>"+
            "<html>");
        About_Label.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        About_Label.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        Exit_Button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Exit_Button.setText("Exit");
        Exit_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Exit_Button.setMaximumSize(new java.awt.Dimension(60, 24));
        Exit_Button.setMinimumSize(new java.awt.Dimension(60, 24));
        Exit_Button.setPreferredSize(new java.awt.Dimension(50, 24));
        Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout About_PanelLayout = new javax.swing.GroupLayout(About_Panel);
        About_Panel.setLayout(About_PanelLayout);
        About_PanelLayout.setHorizontalGroup(
            About_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(About_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(About_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, About_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Exit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        About_PanelLayout.setVerticalGroup(
            About_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(About_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(About_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(Exit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(About_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(About_Panel, 214, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_ButtonActionPerformed
        dispose();
    }//GEN-LAST:event_Exit_ButtonActionPerformed

    /**
     */
    public static void about() {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try 
        {
            javax.swing.UIManager.setLookAndFeel(Info.getClassName());
        }
        catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) 
        {
            JOptionPane.showMessageDialog(null, "Failed to Change Theme !", "Error", JOptionPane.ERROR_MESSAGE);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new About().setVisible(true);
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel About_Label;
    private javax.swing.JPanel About_Panel;
    private javax.swing.JButton Exit_Button;
    // End of variables declaration//GEN-END:variables
}
