/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package notepad;

import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import static notepad.Themes.Info;

/**
 *
 * @author sachindehury2015@gmail.com
 */
public class Find_Replace extends javax.swing.JFrame {

    /**
     * Creates new form Find_Replace
     */
    public Find_Replace() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Find_Label = new javax.swing.JLabel();
        Replace_Label = new javax.swing.JLabel();
        Find = new javax.swing.JButton();
        Find_All = new javax.swing.JButton();
        Replace = new javax.swing.JButton();
        Replace_All = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Find_TextField = new javax.swing.JTextField();
        Replace_TextField = new javax.swing.JTextField();
        Match_Case_CheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Find/Replace");
        setLocation(new java.awt.Point(500, 200));
        setName("Find_Replace_Frame"); // NOI18N
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        Find_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Find_Label.setText("Find :");

        Replace_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Replace_Label.setText("Replace :");

        Find.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Find.setText("Find");
        Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindActionPerformed(evt);
            }
        });

        Find_All.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Find_All.setText("Find Next");
        Find_All.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Find_AllActionPerformed(evt);
            }
        });

        Replace.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Replace.setText("Replace");
        Replace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReplaceActionPerformed(evt);
            }
        });

        Replace_All.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Replace_All.setText("Replace All");
        Replace_All.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Replace_AllActionPerformed(evt);
            }
        });

        Cancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        Find_TextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Find_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Find_TextFieldActionPerformed(evt);
            }
        });

        Replace_TextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Replace_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Replace_TextFieldActionPerformed(evt);
            }
        });

        Match_Case_CheckBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Match_Case_CheckBox.setText("Match Case");
        Match_Case_CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Match_Case_CheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Find_Label)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Replace_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(Find_TextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Replace_Label)
                            .addComponent(Match_Case_CheckBox))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Find_All, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Find, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Replace, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Replace_All)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Find)
                        .addGap(9, 9, 9)
                        .addComponent(Find_All)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Replace))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Find_Label)
                            .addComponent(Find_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Replace_Label)
                            .addComponent(Replace_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Replace_All)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Cancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Match_Case_CheckBox)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Find_Replace");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindActionPerformed
        int select_start=notepad.Notepad.Text_area.getText().indexOf(Find_TextField.getText());
        if(select_start==-1)
        {
            start=0;
            JOptionPane.showMessageDialog(null, "Could not Find !");
        }
        else if(select_start==notepad.Notepad.Text_area.getText().lastIndexOf(Find_TextField.getText()))
        {
            start=0;
        }
        int select_end=select_start+Find_TextField.getText().length();
        notepad.Notepad.Text_area.select(select_start, select_end);
    }//GEN-LAST:event_FindActionPerformed

    private void Match_Case_CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Match_Case_CheckBoxActionPerformed
        JOptionPane.showMessageDialog(null, "Still in Beta !");
    }//GEN-LAST:event_Match_Case_CheckBoxActionPerformed

    private void Replace_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Replace_TextFieldActionPerformed
    }//GEN-LAST:event_Replace_TextFieldActionPerformed

    private void Find_AllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Find_AllActionPerformed
        try 
        {
            notepad.Notepad.Text_area.getSelectedText().equals("");
        } catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
        try 
        {
            int select_start=notepad.Notepad.Text_area.getText().indexOf(Find_TextField.getText());
            int select_end=select_start+Find_TextField.getText().length();
            notepad.Notepad.Text_area.select(select_start, select_end);
            start=select_end+1;
            if(select_start==notepad.Notepad.Text_area.getText().lastIndexOf(Find_TextField.getText()))
            {
                start=0;
            }
        }
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Find_AllActionPerformed

    private void ReplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReplaceActionPerformed
        try 
        {
            FindActionPerformed(evt);
            notepad.Notepad.Text_area.replaceSelection(Replace_TextField.getText());
        }
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ReplaceActionPerformed

    private void Replace_AllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Replace_AllActionPerformed
        try 
        {
            Find_AllActionPerformed(evt);
            notepad.Notepad.Text_area.setText(notepad.Notepad.Text_area.getText().replaceAll(Find_TextField.getText(),Replace_TextField.getText()));
        }
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Replace_AllActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void Find_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Find_TextFieldActionPerformed
    }//GEN-LAST:event_Find_TextFieldActionPerformed

    /**
     */
    public static void Find_Replace() {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try 
        {
            javax.swing.UIManager.setLookAndFeel(Info.getClassName());
        }
        catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) 
        {
            JOptionPane.showMessageDialog(null, "Failed to Change Theme !", "Error", JOptionPane.ERROR_MESSAGE);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Find_Replace().setVisible(true);
        });
    }
    
    int start;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Find;
    private javax.swing.JButton Find_All;
    private javax.swing.JLabel Find_Label;
    private javax.swing.JTextField Find_TextField;
    private javax.swing.JCheckBox Match_Case_CheckBox;
    private javax.swing.JButton Replace;
    private javax.swing.JButton Replace_All;
    private javax.swing.JLabel Replace_Label;
    private javax.swing.JTextField Replace_TextField;
    // End of variables declaration//GEN-END:variables
}
