/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package notepad;

import java.io.File;
import java.io.FileWriter;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import static notepad.Notepad.Text_area;
import static notepad.Notepad.n;
import static notepad.Notepad.path;
import static notepad.Themes.Info;

/**
 *
 * @author sachindehury2015@gmail.com
 */
public class Save_File extends javax.swing.JFrame {

    /**
     * Creates new form File_Rename
     */
    public Save_File() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Save_File = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Save File");
        setLocation(new java.awt.Point(500, 200));
        setName("Open_File_Frame"); // NOI18N
        setType(java.awt.Window.Type.UTILITY);

        Save_File.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        Save_File.setApproveButtonToolTipText("");
        Save_File.setCurrentDirectory(new java.io.File("E:\\"));
            Save_File.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            Save_File.setSelectedFile(new java.io.File("E:\\Untitled.txt"));
            Save_File.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Save_FileActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Save_File, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Save_File, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
            );

            getAccessibleContext().setAccessibleParent(this);

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void Save_FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_FileActionPerformed
        if (evt.getActionCommand().equalsIgnoreCase("CancelSelection")) 
        {
            dispose();
            return;
        }
        File MyFile=Save_File.getSelectedFile();
        try (FileWriter fw = new FileWriter(MyFile)) 
        {
            fw.write(Text_area.getText());
            path=MyFile.getPath();
            notepad.Notepad.name=MyFile.getName()+" - NotePad";
            n.setTitle(notepad.Notepad.name);
            dispose();
        }
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, "Failed to Save the File !", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Save_FileActionPerformed

    /**
     */
    public static void Save_File() {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try 
        {
            javax.swing.UIManager.setLookAndFeel(Info.getClassName());
        }
        catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) 
        {
            JOptionPane.showMessageDialog(null, "Failed to Change Theme !", "Error", JOptionPane.ERROR_MESSAGE);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Save_File().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser Save_File;
    // End of variables declaration//GEN-END:variables
}
